apiVersion: v1
kind: Service
metadata:
  name: ryha-searxng-service
  namespace: ryha-searxng
  labels:
    app: ryha-ultra-searxng
    component: service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  selector:
    app: ryha-ultra-searxng
    component: searxng
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  sessionAffinity: None
  externalTrafficPolicy: Cluster