apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ryha-searxng-pdb
  namespace: ryha-searxng
  labels:
    app: ryha-ultra-searxng
    component: pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: ryha-ultra-searxng
      component: searxng